export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE';

export const APP_GLOBAL_MESSAGE = 'APP_GLOBAL_MESSAGE';